#!/bin/bash

echo "=== shrmpl-cicd echo test ==="
echo "SHRMPL_HOOK_GUID=$SHRMPL_HOOK_GUID"
echo "SHRMPL_DELIVERY_ID=$SHRMPL_DELIVERY_ID"
echo "SHRMPL_TRIGGER_BRANCH=$SHRMPL_TRIGGER_BRANCH"
echo "SHRMPL_TRIGGER_EVENT=$SHRMPL_TRIGGER_EVENT"
echo "SHRMPL_TRIGGER_REPO=$SHRMPL_TRIGGER_REPO"
echo "SHRMPL_TRIGGER_COMMIT=$SHRMPL_TRIGGER_COMMIT"
echo "SHRMPL_TRIGGER_TIMESTAMP=$SHRMPL_TRIGGER_TIMESTAMP"
echo "=== done ==="
